In [31]:
import pandas as pd 
import numpy as np

In [32]:
df=pd.read_csv('finalTrain.csv')

In [33]:
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45584 entries, 0 to 45583
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45584 non-null  object
 1   Delivery_person_ID           45584 non-null  object
 2   Delivery_person_Age          43730 non-null  float64
 3   Delivery_person_Ratings      43676 non-null  float64
 4   Restaurant_latitude          45584 non-null  float64
 5   Restaurant_longitude         45584 non-null  float64
 6   Delivery_location_latitude   45584 non-null  float64
 7   Delivery_location_longitude  45584 non-null  float64
 8   Order_Date                   45584 non-null  object
 9   Time_Orderd                  43853 non-null  object
 10  Time_Order_picked            45584 non-null  object
 11  Weather_conditions           44968 non-null  object
 12  Road_traffic_density         44983 non-null  object
 13  Vehicle_condition            45584 non-null  int64
 14  Type_of_order                45584 non-null  object
 15  Type_of_vehicle              45584 non-null  object
 16  multiple_deliveries          44591 non-null  float64
 17  Festival                     45356 non-null  object
 18  City                         44384 non-null  object
 19  Time_taken (min)             45584 non-null  int64
dtypes: float64(7), int64(2), object(11)
memory usage: 7.0+ MB

In [35]:
df.isnull().sum()

ID                                0
Delivery_person_ID                0
Delivery_person_Age            1854
Delivery_person_Ratings        1908
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    1731
Time_Order_picked                 0
Weather_conditions              616
Road_traffic_density            601
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries             993
Festival                        228
City                           1200
Time_taken (min)                  0
dtype: int64

Feature Engineering

In [36]:
#checking the columns and tranform it
#for changing the time datatype we need to change it
#1st slice it remove : to .
df['Time_Orderd']=df["Time_Orderd"].str.replace(":",".")

In [37]:
#and change its type
df['Time_Orderd']=df['Time_Orderd'].astype('float')

In [38]:
#for replacing the ':' by "."
df['Time_Order_picked']=df['Time_Order_picked'].str.replace(':',".")

In [39]:
#then also the data containtwo point that we need to remove
for i in df['Time_Order_picked']:
    string = i
    second_dot_index = string.find('.', string.find('.') + 1)

    if second_dot_index != -1:
        modified_string = string[:second_dot_index] + string[second_dot_index + 1:]
        df['Time_Order_picked']=modified_string
    else:
        pass

In [40]:
#change their data type
df['Time_Order_picked']=df["Time_Order_picked"].astype('float')

In [41]:
df["Time_Order_picked"].head()

0    24.05
1    24.05
2    24.05
3    24.05
4    24.05
Name: Time_Order_picked, dtype: float64

In [42]:
#change its type 
df['Time_Order_picked']=df['Time_Order_picked'].astype('float')

In [45]:
df=df.drop(labels=['ID','Delivery_person_ID'],axis=1)

In [46]:
df.head()

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
0,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21.55,24.05,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14.55,24.05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17.30,24.05,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,9.20,24.05,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19.50,24.05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45584 entries, 0 to 45583
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Delivery_person_Age          43730 non-null  float64
 1   Delivery_person_Ratings      43676 non-null  float64
 2   Restaurant_latitude          45584 non-null  float64
 3   Restaurant_longitude         45584 non-null  float64
 4   Delivery_location_latitude   45584 non-null  float64
 5   Delivery_location_longitude  45584 non-null  float64
 6   Order_Date                   45584 non-null  object
 7   Time_Orderd                  43853 non-null  float64
 8   Time_Order_picked            45584 non-null  float64
 9   Weather_conditions           44968 non-null  object
 10  Road_traffic_density         44983 non-null  object
 11  Vehicle_condition            45584 non-null  int64
 12  Type_of_order                45584 non-null  object
 13  Type_of_vehicle              45584 non-null  object
 14  multiple_deliveries          44591 non-null  float64
 15  Festival                     45356 non-null  object
 16  City                         44384 non-null  object
 17  Time_taken (min)             45584 non-null  int64
dtypes: float64(9), int64(2), object(7)
memory usage: 6.3+ MB

In [48]:
x=df.drop(labels=['Time_taken (min)'],axis=1)
y=df['Time_taken (min)']

In [16]:
misaaing_values={'numeric_handdle':['Delivery_person_Age','Delivery_person_Ratings','multiple_deliveries'],
                 'min_max_handdle':['Weather_conditions','Road_traffic_density','Festival','City','Time_Orderd'],
                 }

In [49]:
numerical_col=x.select_dtypes(exclude='object').columns
catagorical_col=x.select_dtypes(include='object').columns

In [50]:
numerical_col

Index(['Delivery_person_Age', 'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'Time_Orderd', 'Time_Order_picked',
       'Vehicle_condition', 'multiple_deliveries'],
      dtype='object')

In [51]:
catagorical_col

Index(['Order_Date', 'Weather_conditions', 'Road_traffic_density',
       'Type_of_order', 'Type_of_vehicle', 'Festival', 'City'],
      dtype='object')

In [52]:
df['Time_Order_picked']

0        24.05
1        24.05
2        24.05
3        24.05
4        24.05
         ...
45579    24.05
45580    24.05
45581    24.05
45582    24.05
45583    24.05
Name: Time_Order_picked, Length: 45584, dtype: float64

In [53]:
df['Time_Order_picked'].nunique()

1

In [54]:
df.shape

(45584, 18)

In [55]:
one_columns=['Road_traffic_density','Festival']
ohe_columns=['Type_of_order','Type_of_vehicle','City','Weather_conditions']
top_10_ohe=['Delivery_person_ID','Order_Date','Time_Orderd','Time_Order_picked']

In [56]:
df['Weather_conditions'].unique()

array(['Fog', 'Stormy', 'Sandstorms', 'Windy', 'Cloudy', 'Sunny', nan],
      dtype=object)

In [57]:
traffic_cat=['Jam', 'High', 'Medium', 'Low']
#weather_cat=['Fog', 'Stormy', 'Sandstorms', 'Windy', 'Cloudy', 'Sunny']
festivel_cat=['Yes','No']

In [ ]:
def ohe_many_cat(data, dataset):
    for i in data:
        top_10 = [x for x in dataset[i].value_counts().sort_values(ascending=False).head(10).index]
        for label in top_10:
            dataset[label] = np.where(dataset[i] == label, 1, 0)
        dataset[[i]+top_10].head(20)

In [58]:
from sklearn.impute import SimpleImputer ##for handling the missing values of the data
from sklearn.preprocessing import StandardScaler ##handling feature sacling
from sklearn.preprocessing import OrdinalEncoder ## for ordinal encoding
from sklearn.preprocessing import OneHotEncoder  ## for OneHot Encoding
#for creating pipelines 
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [59]:
##
num_pipeline=Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='median')),
        ('scaler',StandardScaler())
    ]
)

In [60]:
cat_pipeline_one=Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy="most_frequent")),
        ('ordinalencoder',OrdinalEncoder(categories=[traffic_cat,festivel_cat])),
        ('scaler',StandardScaler())
    ]
)

In [61]:
cat_pipeline_ohe=Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy="most_frequent")),
        ('onehotencoder',OneHotEncoder(sparse=False,drop='first')),
        ('scaler',StandardScaler())
        
    ]

    
)

In [ ]:
'''
top_10_pipeline=Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='most_frequent')),
        ('top_10',ohe_many_cat(top_10_ohe,df))
    ]
)
'''

In [62]:
preprocessor=ColumnTransformer(
    [
        ('num_pipeline',num_pipeline,numerical_col),
        ('cat_pipeline_one',cat_pipeline_one,one_columns),
        ('cat_pipeline_ohe',cat_pipeline_ohe,ohe_columns)
       
]
)

Train Test Spliting

In [64]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=40)

In [65]:
x_train.head()

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City
34285,35.0,3.9,12.970324,77.645748,13.100324,77.775748,31-03-2022,19.100000,24.05,Stormy,Jam,1,Drinks,scooter,1.0,No,Metropolitian
14513,37.0,4.5,21.160522,72.771477,21.290522,72.901477,20-03-2022,18.200000,24.05,Windy,Medium,1,Meal,motorcycle,1.0,No,Urban
40479,37.0,5.0,13.022394,80.242439,13.062394,80.282439,30-03-2022,0.666667,24.05,Sandstorms,Medium,2,Buffet,scooter,1.0,No,Metropolitian
37130,39.0,4.5,17.431477,78.400350,17.451477,78.420350,05-03-2022,10.300000,24.05,Fog,Low,2,Buffet,scooter,1.0,No,Urban
28136,36.0,4.4,18.533811,73.899315,18.603811,73.969315,12-03-2022,21.550000,24.05,Stormy,Jam,0,Snack,motorcycle,0.0,No,Metropolitian

In [66]:
x_train.shape

(31908, 17)

In [67]:
x_train=pd.DataFrame(preprocessor.fit_transform(x_train),columns=preprocessor.get_feature_names_out())
x_test=pd.DataFrame(preprocessor.transform(x_test),columns=preprocessor.get_feature_names_out())

c:\Users\pratik terkar\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [69]:
x_train

,num_pipeline__Delivery_person_Age,num_pipeline__Delivery_person_Ratings,num_pipeline__Restaurant_latitude,num_pipeline__Restaurant_longitude,num_pipeline__Delivery_location_latitude,num_pipeline__Delivery_location_longitude,num_pipeline__Time_Orderd,num_pipeline__Time_Order_picked,num_pipeline__Vehicle_condition,num_pipeline__multiple_deliveries,...,cat_pipeline_ohe__Type_of_vehicle_electric_scooter,cat_pipeline_ohe__Type_of_vehicle_motorcycle,cat_pipeline_ohe__Type_of_vehicle_scooter,cat_pipeline_ohe__City_Semi-Urban,cat_pipeline_ohe__City_Urban,cat_pipeline_ohe__Weather_conditions_Fog,cat_pipeline_ohe__Weather_conditions_Sandstorms,cat_pipeline_ohe__Weather_conditions_Stormy,cat_pipeline_ohe__Weather_conditions_Sunny,cat_pipeline_ohe__Weather_conditions_Windy
0,0.953968,-2.252513,-0.491402,0.323979,-0.593934,0.328146,0.426205,-3.552714e-15,-0.020638,0.441566,...,-0.302747,-1.172826,1.407064,-0.059616,-0.534490,-0.471382,-0.444183,2.243158,-0.435302,-0.441297
1,1.304477,-0.421645,0.507563,0.110645,0.523156,0.097130,0.287613,-3.552714e-15,-0.020638,0.441566,...,-0.302747,0.852641,-0.710700,-0.059616,1.870942,-0.471382,-0.444183,-0.445800,-0.435302,2.266048
2,1.304477,1.104079,-0.485051,0.437629,-0.599107,0.446951,-2.412369,-3.552714e-15,1.172327,0.441566,...,-0.302747,-1.172826,1.407064,-0.059616,-0.534490,-0.471382,2.251326,-0.445800,-0.435302,-0.441297
3,1.654985,-0.421645,0.052728,0.357006,-0.000465,0.358697,-0.928919,-3.552714e-15,1.172327,0.441566,...,-0.302747,-1.172826,1.407064,-0.059616,1.870942,2.121422,-0.444183,-0.445800,-0.435302,-0.441297
4,1.129222,-0.726789,0.187181,0.160008,0.156706,0.147740,0.803484,-3.552714e-15,-1.213603,-1.329136,...,-0.302747,0.852641,-0.710700,-0.059616,-0.534490,-0.471382,-0.444183,2.243158,-0.435302,-0.441297
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31903,0.077697,0.188645,0.700829,0.247243,0.731092,0.242206,0.318411,-3.552714e-15,1.172327,0.441566,...,-0.302747,-1.172826,1.407064,-0.059616,-0.534490,-0.471382,-0.444183,2.243158,-0.435302,-0.441297
31904,-0.973829,-1.031934,1.214494,0.242174,1.310953,0.238612,0.341510,-3.552714e-15,1.172327,-1.329136,...,-0.302747,-1.172826,1.407064,-0.059616,-0.534490,-0.471382,-0.444183,-0.445800,-0.435302,-0.441297
31905,-0.272812,0.493790,0.056172,0.355628,0.018389,0.362418,0.634094,-3.552714e-15,1.172327,0.441566,...,-0.302747,0.852641,-0.710700,-0.059616,-0.534490,-0.471382,-0.444183,-0.445800,2.297258,-0.441297
31906,-0.097558,0.798935,0.185498,0.156998,0.160280,0.146376,-2.386703,-3.552714e-15,1.172327,-1.329136,...,-0.302747,0.852641,-0.710700,-0.059616,-0.534490,-0.471382,-0.444183,-0.445800,2.297258,-0.441297
31907,0.778714,0.493790,1.695493,0.244567,1.840645,0.238360,0.495502,-3.552714e-15,1.172327,0.441566,...,-0.302747,-1.172826,1.407064,-0.059616,1.870942,-0.471382,-0.444183,-0.445800,-0.435302,-0.441297

Model Traning

In [70]:
##model traning
from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [71]:
regression=LinearRegression()
regression.fit(x_train,y_train)

LinearRegression()

In [72]:
regression.coef_

array([ 2.20803407e+00, -2.33559884e+00,  4.89626400e-02, -3.49623323e-01,
       -2.47832838e-02,  3.08342876e-01,  4.00122730e-01,  3.33066907e-16,
       -1.73982622e+00,  1.80188239e+00, -3.17244451e+00, -1.39003356e+00,
       -2.22943813e-03,  3.44562600e-02,  4.39920254e-02, -3.28742763e-01,
       -7.69543844e-01, -1.04318855e+00,  6.42184893e-01, -8.91584904e-01,
        8.78444811e-02, -9.74997426e-01, -1.01788485e+00, -2.21097007e+00,
       -9.36925699e-01])

In [73]:
regression.intercept_

26.30882537294722

In [74]:
import numpy as np
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [75]:
## Train multiple models

models={
    'LinearRegression':LinearRegression(),
    'Lasso':Lasso(),
    'Ridge':Ridge(),
    'Elasticnet':ElasticNet()
}
trained_model_list=[]
model_list=[]
r2_list=[]

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(x_train,y_train)

    #Make Predictions
    y_pred=model.predict(x_test)

    mae, rmse, r2_square=evaluate_model(y_test,y_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model Training Performance')
    print("RMSE:",rmse)
    print("MAE:",mae)
    print("R2 score",r2_square*100)

    r2_list.append(r2_square)
    
    print('='*35)
    print('\n')

LinearRegression
Model Training Performance
RMSE: 6.277128607486874
MAE: 5.020172127480881
R2 score 55.76261546251755
===================================


Lasso
Model Training Performance
RMSE: 6.945458575130699
MAE: 5.561484774696243
R2 score 45.8411742570021
===================================


Ridge
Model Training Performance
RMSE: 6.277140383123607
MAE: 5.020180150936377
R2 score 55.762449487310896
===================================


Elasticnet
Model Training Performance
RMSE: 6.953012913306687
MAE: 5.592838492437455
R2 score 45.723296774604904
===================================